esphome:
  name: lantern-frontyard
  friendly_name: lantern-frontyard

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.226
    gateway: 192.168.1.1
    subnet: 255.255.255.0
api:
  encryption:
    key: !secret lantern_frontyard_enc_key

logger:

ota:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Lantern Frontyard (Sonoff Basic Button)"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Lantern Frontyard (Sonoff Basic Relay)"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes