esphome:
  name: sprinkler

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret sprinkler_enc_key 

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinkler Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:
    
switch:
  - platform: gpio
    pin: D1
    name: "Sprinkler Zone 4"
    inverted: true
  - platform: gpio
    pin: D2
    name: "Sprinkler Zone 2"
    inverted: true
  - platform: gpio
    pin: D3
    name: "Sprinkler Zone 3"
    inverted: true
  - platform: gpio
    pin: D4
    name: "Sprinkler Zone 1 (Hecke)"
    inverted: true
